# Generated by Django 4.0.4 on 2022-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Заказанная книга',
                'verbose_name_plural': 'Заказанные книги',
                'db_table': 'ordered_books',
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('maximum_delivery_date', models.DateField(null=True)),
                ('reception_type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Запись о заказе',
                'verbose_name_plural': 'Записи о заказе',
                'db_table': 'order_entries',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'db_table': 'order_statuses',
                'ordering': ['id'],
            },
        ),
    ]
