# Generated by Django 4.0.4 on 2022-05-07 12:32

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderentry_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderentry',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='reception_type',
            field=models.CharField(max_length=10, validators=[orders.validators.validate_reception_type]),
        ),
    ]
