# Generated by Django 4.0.4 on 2022-05-05 19:47

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='book_cover_images/', validators=[books.validators.validate_cover_image]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, validators=[books.validators.validate_isbn]),
        ),
    ]
