# Generated by Django 4.0.4 on 2022-05-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('is_functional', models.BooleanField(default=True)),
                ('delivery_available_cities', models.ManyToManyField(related_name='delivery_available_cities', to='storages.city')),
                ('location_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_cities', to='storages.city')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'db_table': 'storages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StorageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.PositiveIntegerField()),
                ('last_updated', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage')),
            ],
            options={
                'verbose_name': 'Запись о хранении',
                'verbose_name_plural': 'Записи о хранении',
                'db_table': 'storage_entries',
                'ordering': ['-last_updated'],
            },
        ),
    ]
