# Generated by Django 4.0.4 on 2022-05-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_alter_storage_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storage',
            managers=[
            ],
        ),
    ]
