# Generated by Django 4.0.4 on 2022-05-05 16:40

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_paymentcard_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookstoreuser',
            managers=[
                ('users', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='coupon',
            managers=[
                ('coupons', django.db.models.manager.Manager()),
            ],
        ),
    ]
