# Generated by Django 4.0.4 on 2022-05-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_bookstoreuser_managers_alter_coupon_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookstoreuser',
            managers=[
            ],
        ),
    ]
