# Generated by Django 4.0.4 on 2022-05-06 18:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_alter_book_isbn'),
        ('user', '0005_alter_bookstoreuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookstoreuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bookstoreuser',
            name='user_addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='user.userorderaddress'),
        ),
        migrations.AlterField(
            model_name='bookstoreuser',
            name='user_coupons',
            field=models.ManyToManyField(blank=True, related_name='user_coupons', to='user.coupon'),
        ),
        migrations.AlterField(
            model_name='bookstoreuser',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='books.book'),
        ),
    ]
