# Generated by Django 4.0.4 on 2022-05-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_alter_storage_managers'),
        ('user', '0006_alter_bookstoreuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='userorderaddress',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storages.city'),
            preserve_default=False,
        ),
    ]
