# Generated by Django 4.0.4 on 2022-05-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_supplyentry_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplyentry',
            managers=[
            ],
        ),
    ]
